name: Build macOS and Windows App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python on macOS
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies on macOS
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed main.py
          
      - name: Upload macOS .app file
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python on Windows
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies on Windows
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed main.py
          
      - name: Upload Windows .exe file
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist
